### ISSUE TITLE
Failure as a Professional coder.

### ISSUE THREAD

**Issue by Jeftaei** [fiveman1/rbhopdog#2]
https://github.com/fiveman1/rbhopdog/blob/a1be4c79d8157f24bc0a2e6c3b631ddd800a35aa/src/modules/strafes_base.py#L76

As you can see in this line here, Fiveman1 uses `if style != Style.FASTE and style != Style.SUSTAIN` when obviously he should be using a OR statement, or even `if style not in (Style.FASTE, Style.SUSTAIN)`.

And this is the man you are all trusting with his Rat of a bot in ur servers? You should all be ashamed.

**Comment by fiveman1** [comment]
well a real improvement would be to just write out the default styles explicitly but this is just semantics
